version: "3.9"

networks:
  42_inception:
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      device: /home/trhee/data/wordpress
      o: bind
      type: none
  database: 
    driver: local
    driver_opts:
      device: /home/trhee/data/mariadb
      o: bind
      type: none


services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - 42_inception
    restart: always
    env_file: .env
  mariadb:  
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - 42_inception
    restart: always
    env_file: .env
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - 42_inception
    restart: always
    env_file: .env